apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cvnts1.fullname" . }}
spec:
  dnsNames:
  - "{{ .Values.ingress.domain }}"
  duration: 2160h0m0s
  issuerRef:
{{- toYaml .Values.certificate.issuerRef | nindent 4 }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048          
  renewBefore: 720h0m0s
  secretName: {{ include "cvnts1.fullname" . }}-cert
  subject:
    organizations:
    - CVNTS1
  usages:
  - server auth
  - client auth
