apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cvnts1.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "cvnts1.fullname" . }}-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cvnts1.fullname" . }}-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cvnts1.fullname" . }}-server
    spec:
      serviceAccountName: {{ include "cvnts1.fullname" . }}
      containers:
        - name: server
          image: {{ .Values.server.registry }}:{{ .Values.server.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/health
              port: http
          readinessProbe:
            httpGet:
              path: /-/health
              port: http
          env:
            - name: HEALTH_MESSAGE
              value: {{ .Values.server.health_message }}