apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cvnts1.fullname" . }}-server
  {{ if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{ end }}
  labels:
    app.kubernetes.io/name: {{ include "cvnts1.fullname" . }}-server
spec:
  tls:
  - hosts:
      - {{ .Values.ingress.domain }}
    secretName: {{ include "cvnts1.fullname" . }}-cert
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cvnts1.fullname" . }}-server
                port:
                  number: 80
