apiVersion: v1
kind: Service
metadata:
  name: {{ include "cvnts1.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "cvnts1.fullname" . }}-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "cvnts1.fullname" . }}-server
